In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
## your code
arr = np.arange(1, 21)
res = 2 ** arr / arr
res

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [5]:
## your code
z = np.arange(0,6)
res = sum(0.1 ** (3 * z) * 0.2 ** (4 * z))
print(res)

1.00000160000256


**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [6]:
## your code
M = np.zeros((8, 8))
M[::2, ::2] = 1
M[1::2, 1::2] = 1
M

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [21]:
X = np.random.random((5, 2))
## your code
r = np.sqrt(np.array(X[::,0]**2 + X[::,1]**2))
phi = np.arctan(X[:,1] / X[:,0])
res = np.vstack((r, phi)).T
print(res)

[[1.02641019 0.89284152]
 [0.67648969 0.37934922]
 [0.8813434  1.38953992]
 [1.2213728  0.93319097]
 [0.57910717 0.04864015]]


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [24]:
X = np.random.random((10, 10))
value = np.argmax(X)
row = value // 10
column = value % 10
## your code

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [25]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code
distances = np.sum((X - y) * (X - y), axis=1)
value = np.argmin(distances)
print(value)
## your code


7


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [38]:
## your code
def f(x):
    if x < 0:
        return x ** 2 + 2 * x + 6
    if 0 <= x <= 2:
        return x + 6
    if x >= 2:
        return x ** 2 + 4 * x - 4

x = np.linspace(-3, 3, 7)

res = list(map(f, x))

print(res)

[9.0, 6.0, 5.0, 6.0, 7.0, 8.0, 17.0]


**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [50]:
from cmath import isclose
import math
X = np.random.random((10, 10))

## your code

means = np.mean(X, axis=0)
X_0 = X - means

print(np.mean(X_0, axis=0))

[ 1.11022302e-17 -2.22044605e-17 -2.22044605e-17 -7.77156117e-17
  3.33066907e-17 -3.33066907e-17 -5.55111512e-17 -2.22044605e-17
  7.77156117e-17 -2.22044605e-17]


**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [54]:
X = np.random.normal(loc=5, scale=2., size=1000)

x_mean = X.mean()
x_var = X.var()
print(x_mean, x_var)

4.987461469049508 3.8035911995062808


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [71]:
## your code
x = np.ones((5, 5), dtype=int) * np.arange(5, dtype=int)
x += x.T
x = x % 5
x

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [65]:
## your code
def new_sample(x, c):    
    s = np.sum(x)
    z = s * np.random.random(c)
    res = np.argmin((np.cumsum(x) <= z.reshape(-1, 1)), axis=1)
    return res

In [70]:
print(new_sample([50, 3, 1, 7, 20], 5))

[0 0 3 3 0]
